C=$(tput setaf 14)
R=$(tput setaf 1)
printf ${C}
echo "                               .:xxxxxxxx:. "
echo "                            .xxxxxxxxxxxxxxxx." 
echo "                           :xxxxxxxxxxxxxxxxxxx:." 
echo "                          .xxxxxxxxxxxxxxxxxxxxxxx:" 
echo "                         :xxxxxxxxxxxxxxxxxxxxxxxxx: "
echo "                         xxxxxxxxxxxxxxxxxxxxxxxxxxX: "
echo "                         xxx:::xxxxxxxx::::xxxxxxxxx: "
echo "                        .xx:   ::xxxxx:     :xxxxxxxx "
echo "                        :xx  ${R}x.${C}  xxxx:  ${R}xx.${C}  xxxxxxxx "
echo "                        :xx ${R}xxx${C}  xxxx: ${R}xxxx${C}  :xxxxxxx "
echo "                        'xx ${R}'xx${C}  xxxx:. ${R}xx'${C}  xxxxxxxx "
echo "                         xx ::::::xx:::::.   xxxxxxxx "
echo "                         xx:::::.::::.:::::::xxxxxxxx "
echo "                         :x'::::'::::':::::':xxxxxxxxx. "
echo "                         :xx.::::::::::::'   xxxxxxxxxx "
echo "                         :xx: '::::::::'     :xxxxxxxxxx. "
echo "                        .xx     '::::'        'xxxxxxxxxx. "
echo "                      .xxxx                     'xxxxxxxxx. "
echo "                    .xxxx                         'xxxxxxxxx. "
echo "                  .xxxxx:                          xxxxxxxxxx. "
echo "                 .xxxxx:'                          xxxxxxxxxxx. "
echo "                .xxxxxx:::.           .       ..:::_xxxxxxxxxxx:. "
echo "               .xxxxxxx''      ':::''            ''::xxxxxxxxxxxx. "
echo "               xxxxxx            :                  '::xxxxxxxxxxxx "
echo "              :xxxx:'            :                    'xxxxxxxxxxxx: "
echo "             .xxxxx              :                     ::xxxxxxxxxxxx "
echo "             xxxx:'                                    ::xxxxxxxxxxxx "
echo "             xxxx               .                      ::xxxxxxxxxxxx. "
echo "         .:xxxxxx               :                      ::xxxxxxxxxxxx:: "
echo "         xxxxxxxx               :                      ::xxxxxxxxxxxxx: "
echo "         xxxxxxxx               :                      ::xxxxxxxxxxxxx: "
echo "         ':xxxxxx               '                      ::xxxxxxxxxxxx:' "
echo "           .:. xx:.                                   .:xxxxxxxxxxxxx' "
echo "         ::::::.'xx:.            :                  .:: xxxxxxxxxxx': "
echo " .:::::::::::::::.'xxxx.                            ::::'xxxxxxxx':::. "
echo " ::::::::::::::::::.'xxxxx                          :::::.'.xx.'::::::. "
echo " ::::::::::::::::::::.'xxxx:.                       :::::::.'':::::::::   "
echo " ':::::::::::::::::::::.'xx:'                     .'::::::::::::::::::::.. "
echo "   :::::::::::::::::::::.'xx                    .:: ::::::::::::::::::::::: "
echo " .:::::::::::::::::::::::. xx               .::xxxx ::::::::::::::::::::::: "
echo " :::::::::::::::::::::::::.'xxx..        .::xxxxxxx ::::::::::::::::::::' "
echo " '::::::::::::::::::::::::: xxxxxxxxxxxxxxxxxxxxxxx :::::::::::::::::' "
echo "   '::::::::::::::::::::::: xxxxxxxxxxxxxxxxxxxxxxx :::::::::::::::' "
echo "       ':::::::::::::::::::_xxxxxx::'''::xxxxxxxxxx '::::::::::::' "
echo "            ':::.:::::::::'                          '._::::::_.'  "

